owner: LeastAuthority
repo: infrastructure-upptime

sites:
  - name: Grafana - LA
    icon: https://raw.githubusercontent.com/LeastAuthority/infrastructure-upptime/master/assets/grafana-icon.png
    url: $URL_MONITORING_LA
  - name: Grafana - MW
    icon: https://raw.githubusercontent.com/LeastAuthority/infrastructure-upptime/master/assets/grafana-icon.png
    url: $URL_MONITORING_MW
  - name: Grafana - PS
    icon: https://raw.githubusercontent.com/LeastAuthority/infrastructure-upptime/master/assets/grafana-icon.png
    url: $URL_MONITORING_PS
  - name: Magic Wormhole - mailbox STAGE
    url: https://mailbox.stage.mw.leastauthority.com/
  - name: Magic Wormhole - relay STAGE
    url: https://transit.stage.mw.leastauthority.com/
  - name: LimeSurvey - STAGE
    url: $URL_LIMESURVEY_STAGE
    expectedStatusCodes:
      - 200
  - name: SnipeIT - STAGE
    url: $URL_SNIPEIT_STAGE
    expectedStatusCodes:
      - 200
  - name: SuiteCRM - STAGE
    url: $URL_SUITECRM_STAGE
    expectedStatusCodes:
      - 200
  - name: Zulip - EVAL
    url: $URL_ZULIP_EVAL
    expectedStatusCodes:
      - 200

status-website:
  baseUrl: /infrastructure-upptime
  logoUrl: https://raw.githubusercontent.com/LeastAuthority/infrastructure-upptime/master/assets/upptime-icon.svg
  name: Infrastructure
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by [GitHub](https://github.com/LeastAuthority/infrastructure-upptime)."
  introMessage: This site monitors the resources powering the infrastructure of [Least Authority](https://leastauthority.com/)
  navbar:
    - title: End Users
      href: /end-users-upptime
    - title: Org Members
      href: /org-members-upptime
    - title: Infrastructure
      href: /infrastructure-upptime

# Do not delete issues, just close them, so we can investigate intermittent problems
skipDeleteIssues: true

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
