owner: LeastAuthority
repo: infrastructure-upptime

sites:
  - name: Grafana - LA
    icon: https://raw.githubusercontent.com/LeastAuthority/infrastructure-upptime/master/assets/grafana-icon.png
    url: $URL_MONITORING_LA
  - name: Grafana - MW
    icon: https://raw.githubusercontent.com/LeastAuthority/infrastructure-upptime/master/assets/grafana-icon.png
    url: $URL_MONITORING_MW
  - name: Grafana - HC
    icon: https://raw.githubusercontent.com/LeastAuthority/infrastructure-upptime/master/assets/grafana-icon.png
    url: $URL_MONITORING_HC
  - name: Grafana - PS
    icon: https://raw.githubusercontent.com/LeastAuthority/infrastructure-upptime/master/assets/grafana-icon.png
    url: $URL_MONITORING_PS

status-website:
  baseUrl: /infrastructure-upptime
  logoUrl: https://raw.githubusercontent.com/LeastAuthority/infrastructure-upptime/master/assets/upptime-icon.svg
  name: Infrastructure
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by [GitHub](https://github.com/LeastAuthority/infrastructure-upptime)."
  introMessage: This site monitors the resources powering the infrastructure of [Least Authority](https://leastauthority.com/)
  navbar:
    - title: End Users
      href: /end-users-upptime
    - title: Org Members
      href: /org-members-upptime
    - title: Infrastructure
      href: /infrastructure-upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
